# Generated by Django 3.2.15 on 2022-08-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(db_index=True, default='test', max_length=50, verbose_name='имя'),
            preserve_default=False,
        ),
    ]
