# Generated by Django 3.2.15 on 2022-08-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Необработанный'), ('cooking', 'Готовится'), ('delivering', 'В доставке'), ('complete', 'Завершён')], default='new', max_length=10),
        ),
    ]
