# Generated by Django 3.2.15 on 2022-08-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Необработанный'), ('cooking', 'Готовится'), ('delivering', 'В доставке'), ('complete', 'Завершён')], db_index=True, default='new', max_length=10, verbose_name='статус'),
        ),
    ]
