# Generated by Django 3.2.15 on 2022-08-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20220818_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymeny',
            field=models.CharField(choices=[('cash', 'Наличностью'), ('card', 'Электронно')], db_index=True, default='cash', max_length=4, verbose_name='способ оплаты'),
        ),
    ]
