# Generated by Django 3.2.15 on 2022-08-18 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[(0, 'Наличностью'), (1, 'Электронно')], db_index=True, default='cash', max_length=4, verbose_name='способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='foodcartapp.restaurant', verbose_name='назначенный ресторан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, 'Необработанный'), (1, 'Готовится'), (2, 'В доставке'), (3, 'Завершён')], db_index=True, default='new', max_length=10, verbose_name='статус'),
        ),
    ]
