# Generated by Django 3.2.15 on 2022-08-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='restaurant',
            new_name='assigned_restaurant',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.IntegerField(choices=[(0, 'Наличностью'), (1, 'Электронно')], db_index=True, verbose_name='способ оплаты'),
        ),
    ]
