# Generated by Django 3.2.15 on 2022-08-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_auto_20220824_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.IntegerField(choices=[(0, 'Наличностью'), (1, 'Электронно')], db_index=True, null=True, verbose_name='способ оплаты'),
        ),
    ]
